language: python

python:
  - "3.6"

env:
  - DEPS="Django>=1.11,<1.12"
  - DEPS="Django>=2.1,<2.2"
  - DEPS="Django>=2.2,<2.3"

install:
  - sudo apt-get update -y
  - sudo apt-get install graphicsmagick libjpeg-dev
  - pip install pipenv codecov
  - pipenv install --dev
  - pipenv run pip install -e .
  - pipenv run pip install $DEPS

script: pipenv run py.test --cov

after_success:
  - codecov
