---
name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          sudo apt-get install -y graphicsmagick libjpeg-dev
          python -m pip install --upgrade pip setuptools
          python -m pip install --upgrade poetry poetry-plugin-export tox tox-gh-actions coverage
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox"
      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v4"
        if: ${{ github.repository_owner == 'stephrdev' }}
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
